#!/bin/bash
# Lets see machine specifications and environments

df -h
free -h
nproc
cat /etc/os*
env

#tg
tg(){
	bot_api=$bot_api # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
	your_telegram_id=$1 # No need to touch 
	msg=$2 # No need to touch
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}

id=$tg_id # Your telegram id
tg $id "Downloads Cache at $date"

curl https://anu.inok189.workers.dev/ccache/ccache.tar.gz -o /tmp/ccache.tar.gz

cd /tmp # Where to download cccahe
ls /tmp
#time aria2c $url -x16 -s50 # Using aria2c for speed haha, ccache will be at /tm>
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
ls /tmp
rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the >

