#!/bin/bash

ls /tmp/rom/out
cat /tmp/rom/out/error.log

cd /tmp

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

#tg
tg(){
	bot_api=$bot_api # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
	your_telegram_id=$1 # No need to touch
	msg=$2 # No need to touch
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}
id=$tg_id # Your telegram id
tg $id "uploading ccache at $(date)"

send_zip=$(ls /tmp/rom/out/target/product/juice/Nusantara*.zip)

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache
cat ~/.config/rclone/rclone.conf

time rclone copy /tmp/rom/out/target/product/juice/Nusantara*.zip inok:juice -P
time rclone copy ccache.tar.gz inok:ccache -P
time rclone copy /tmp/rom/out/error.log inok: -P

#tg
tg(){
	bot_api=$bot_api # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
	your_telegram_id=$1 # No need to touch
	msg=$2 # No need to touch
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}
id=$tg_id # Your telegram id
tg $id "Download ROM Link: [$send_zip](https://anu.inok189.workers.dev/juice/$send_zip)"

#tg
tg(){
	bot_api=$bot_api # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
	your_telegram_id=$1 # No need to touch
	msg=$2 # No need to touch
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}
id=$tg_id # Your telegram id 
tg $id "upload ccache done at $(date)"
